# Python
[tool.black]
line-length = 120
target_version = ["py311"]

[tool.ruff]
line-length = 120
extend-ignore = [
    "ANN002", "ANN003", "ANN101", "ANN102", "D103", "D100", "D101",
    "D203", "D204", "D213", "D215", "D400", "D404", "D406", "D407", "D408", "D409", "D413", "S101"
]  # "E203", "B001", "W503", "R504"
exclude = [".git", "__pycache__", ".mypy_cache", ".pytest_cache", ".venv", ".cache", "test/"]
extend-select = ["E", "F", "ANN", "S", "B", "A", "RET", "D", "W", "I001"]

[tool.ruff.flake8-annotations]
mypy-init-return = true

[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query"]

[tool.ruff.isort]
force-single-line = true

[tool.ruff.per-file-ignores]
"tests/test_" = ["D"]
"*/__init__.py" = ["D104"]

[tool.mypy]
python_version = "3.11"
cache_dir = "/dev/null"
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
show_error_context = true
show_column_numbers = true
show_error_codes = true
local_partial_types = true

[tool.pytest.ini_options]
asyncio_mode = "auto"

# Hooks for non-python files
[tool.sqlfluff.rules]
tab_space_size = 4
max_line_length = 120

# Keywords
[tool.sqlfluff.rules.L010]
capitalisation_policy = "upper"

# Function names
[tool.sqlfluff.rules.L030]
capitalisation_policy = "upper"

# Null & Boolean Literals
[tool.sqlfluff.rules.L040]
capitalisation_policy = "upper"
